# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  python: circleci/python@1.2


jobs:
  #Part of circle
  build-and-test:
    working_directory: /home/circleci/project
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      #- python/install-packages:
      #    pkg-manager: pip
      #    pip-dependency-file: requirements.txt
      - run:
          name: Run tests
          command: pytest

  # part of docker ub
  build-push-docker:
    executor: my-machine
    steps:
      - checkout
      - run:
          name: Build Docker image
          command: docker build -t ${DOCKER_USER}/${DOCKER_NAME}:$CIRCLE_SHA1 .
      - run:
          name: Push Docker Image
          command: |
            echo ${DOCKER_TOKEN} | docker login -u ${DOCKER_USER} --password-stdin
            docker tag ${DOCKER_USER}/${DOCKER_NAME}:${CIRCLE_SHA1} ${DOCKER_USER}/${DOCKER_NAME}:lastest
            docker push ${DOCKER_USER}/${DOCKER_NAME}:${CIRCLE_SHA1}
            docker push ${DOCKER_USER}/${DOCKER_NAME}:lastest

  # part of Heroku
  deploy-dev:
    machine: true
    steps:
      - checkout
      - run:
          name: Build and push Docker image to Heroku
          command: |
            sudo curl https://cli-assets.heroku.com/install.sh | sh
            HEROKU_API_KEY=${HEROKU_TOKEN} heroku container:login
            HEROKU_API_KEY=${HEROKU_TOKEN} heroku container:push -a ${HEROKU_NAME} web
            HEROKU_API_KEY=${HEROKU_TOKEN} heroku container:release -a ${HEROKU_NAME} web



workflows:
  sample:
    jobs:
      - build-and-test
      - build-push-docker
      - deploy-dev

