# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:

  python: circleci/python@1.2


jobs:
  build-and-test:
    working_directory: /home/circleci/project
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
          pip-dependency-file: requirements.txt
      - run:
          name: Run tests
          command: pytest


workflows:
  sample:
    jobs:
      - build-and-test

