# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  python: circleci/python@1.2


jobs:
  #Part of circle
  build-and-test:
    working_directory: /home/circleci/project
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout

      - python/install-packages:
          pkg-manager: pip
          pip-dependency-file: requirements.txt
      - run:
          name: Run tests
          command: pytest

  # part of docker ub
  build-push-docker:
    machine: true
    steps:
      - checkout
      - run:
          name: Build Docker image
          command: docker build -t mlsc63/lettings:$CIRCLE_SHA1
      - run:
          name: Push Docker Image
          command: |
            echo 6eb02bdb-4cfc-4e8e-8faf-566fc72e4c2b | docker login -u mlsc63 --password-stdin
            docker tagmlsc63/lettings:$CIRCLE_SHA1 mlsc63/lettings:lastest
            docker push mlsc63/lettings:$CIRCLE_SHA1
            docker push mlsc63/lettings:lastest
            docker push mlsc63/lettings:lastest

  # part of Heroku
  deploy-dev:
    machine: true
    steps:
      - checkout
      - run:
          name: Build and push Docker image to Heroku
          command: |
            sudo curl https://cli-assets.heroku.com/install.sh | sh
            HEROKU_API_KEY=${HEROKU_TOKEN} heroku container:login
            HEROKU_API_KEY=${HEROKU_TOKEN} heroku container:push -a ${HEROKU_NAME} web
            HEROKU_API_KEY=${HEROKU_TOKEN} heroku container:release -a ${HEROKU_NAME} web



workflows:
  sample:
    jobs:
      - build-and-test
      - build-push-docker
      - deploy-dev

